# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeeEZy_KYOZNgbAR3CC9i6rnWT6B-uLV
"""

# To-Do List Application

def add_task(tasks, task_name):
    """Add a new task to the list."""
    task = {"task": task_name, "completed": False}
    tasks.append(task)
    print(f"Task '{task_name}' added successfully.")

def delete_task(tasks, task_index):
    """Delete a task from the list."""
    if 0 <= task_index < len(tasks):
        removed_task = tasks.pop(task_index)
        print(f"Task '{removed_task['task']}' deleted successfully.")
    else:
        print("Invalid task index.")

def display_tasks(tasks):
    """Display all tasks in the list."""
    if not tasks:
        print("No tasks in the list.")
        return
    print("\nTo-Do List:")
    for index, task in enumerate(tasks, 1):
        status = "Complete" if task["completed"] else "Incomplete"
        print(f"{index}. {task['task']} - {status}")

def mark_task_complete(tasks, task_index):
    """Mark a task as complete."""
    if 0 <= task_index < len(tasks):
        tasks[task_index]["completed"] = True
        print(f"Task '{tasks[task_index]['task']}' marked as complete.")
    else:
        print("Invalid task index.")

def main():
    tasks = []
    while True:
        print("\n--- To-Do List Menu ---")
        print("1. Add Task")
        print("2. Delete Task")
        print("3. Display Tasks")
        print("4. Mark Task as Complete")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == "1":
            task_name = input("Enter the task name: ")
            add_task(tasks, task_name)
        elif choice == "2":
            display_tasks(tasks)
            try:
                task_index = int(input("Enter the task index to delete: ")) - 1
                delete_task(tasks, task_index)
            except ValueError:
                print("Invalid input. Please enter a number.")
        elif choice == "3":
            display_tasks(tasks)
        elif choice == "4":
            display_tasks(tasks)
            try:
                task_index = int(input("Enter the task index to mark complete: ")) - 1
                mark_task_complete(tasks, task_index)
            except ValueError:
                print("Invalid input. Please enter a number.")
        elif choice == "5":
            print("Exiting the application.")
            break
        else:
            print("Invalid choice. Please enter a number from 1 to 5.")

if __name__ == "__main__":
    main()